name: Automated Test, Build and Deploy for BookLah
on:
  push:
    branches:
      - main # Workflow will be triggered whenever there is a push in main branch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code from GitHub Repo
      uses: actions/checkout@v3
      
    - name: Setup Node.js in Ubuntu
      uses: actions/setup-node@v3
      with:
        node-version: 18
        
    - name: Remove existing node_modules folder from cloned project
      run: rm -rf /home/runner/work/BookLah-Jivaka/BookLah-Jivaka/node_modules/*
      
    - name: Install dependencies for based on package.json
      run: npm install
      
    - name: Run tests in "tests" folder
      run: npm test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code from GitHub Repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: docker-compose build

      - name: Push Docker image to Docker Hub
        run: docker-compose push
